<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kartabl_Backend.Domain\Kartabl_Backend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Common\Models\" />
    <Folder Include="Modules\Auth\Commands\" />
    <Folder Include="Modules\Auth\DTOs\" />
    <Folder Include="Modules\Users\Commands\" />
    <Folder Include="Modules\Users\DTOs\" />
    <Folder Include="Modules\Users\Queries\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
