<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kartabl_Backend.Application\Kartabl_Backend.Application.csproj" />
    <ProjectReference Include="..\Kartabl_Backend.Domain\Kartabl_Backend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
